dir=/home/imsuck/Downloads

continue=true

enable-rpc=true
rpc-listen-all=false
rpc-listen-port=6800

rpc-allow-origin-all=true

max-connection-per-server=8
split=8

input-file=/home/imsuck/.config/aria2/aria2.session
save-session=/home/imsuck/.config/aria2/aria2.session
save-session-interval=60
