baseMouseSpeed: 750.0
baseScrollSpeed: 20.0

layers:
  - name: initial
    bindings:
      capslock: tap-hold layer mouse ; capslock ; 200

  - name: mouse
    passThrough: true
    bindings:
      capslock: layer initial
      r: reload-config

      h: move -1  0
      j: move  0  1
      k: move  0 -1
      l: move  1  0

      q: button left
      w: button middle
      e: button right

      leftshift: toggle-layer scroll
      a: speed 0.25
      s: speed 4.0

  - name: scroll
    passThrough: true
    bindings:
      h: scroll left
      j: scroll down
      k: scroll up
      l: scroll right

      q: multi leftshift; button left
      w: multi leftshift; button middle
      e: multi leftshift; button right
