[manager]
prepend_keymap = [
  { on = "!", run = "shell --block '$SHELL'" },

  { on = "o", run = "shell --confirm --orphan 'handlr open \"$0\"'" },
  { on = "e", run = "shell --confirm --block '$EDITOR \"$0\"'" },

  { on = "f", run = "plugin smart-filter" },
  { on = "F", run = "filter" },

  { on = "j", run = "plugin arrow 1" },
  { on = "k", run = "plugin arrow -1" },
  { on = "l", run = "plugin smart-enter" },

  { on = [ "c", "m" ], run = "plugin chmod", desc = "Change file permissions" },
  # TODO: copy image to clipboard
  # { on = [ "c", "i" ], run = "shell --confirm --block 'cat $0 | xclip'"}

  { on = "M", run = "plugin mount" },

  { on = "<C-n>", run = "shell --confirm 'ripdrag -x -i -s 64 \"$@\" 2>/dev/null'" },
]
