[mgr.border_style]
fg = "darkgray"

[mgr.count_copied]
bg = "green"
fg = "black"

[mgr.count_cut]
bg = "red"
fg = "black"

[mgr.count_selected]
bg = "yellow"
fg = "black"

[mgr.tab_active]
bg = "blue"
fg = "black"

[mgr.tab_inactive]
fg = "blue"

[mode.normal_alt]
bg = "darkgray"
fg = "blue"

[mode.normal_main]
bg = "blue"
fg = "black"

[mode.select_alt]
bg = "darkgray"
fg = "green"

[mode.select_main]
bg = "green"
fg = "black"

[mode.unset_alt]
bg = "darkgray"
fg = "magenta"

[mode.unset_main]
bg = "magenta"
fg = "black"

[status.sep_left]
open = ""
close = ""

[status.sep_right]
close = ""
open = ""

[tabs.active]
bg = "blue"
fg = "black"

[tabs.inactive]
bg = "reset"
fg = "blue"

[tabs.sep_inner]
open = ""
close = ""

[tabs.sep_outer]
open = ""
close = ""
