theme = "base16_terminal_edit"

[editor]
line-number = "relative"
color-modes = true
auto-format = false
idle-timeout = 0
shell = ["fish", "-c"]
rulers = [80]
completion-trigger-len = 1
completion-replace = true
bufferline = "multiple"

end-of-line-diagnostics = "hint"

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "block"

[editor.lsp]
display-messages = true
display-inlay-hints = false
display-signature-help-docs = false

[editor.inline-diagnostics]
# cursor-line = "error"

[editor.statusline]
left = ["mode", "spacer", "spinner", "spacer", "version-control", "file-name", "read-only-indicator", "file-modification-indicator", "spacer", "diagnostics"]
right = ["position", "total-line-numbers", "selections", "file-encoding", "file-line-ending"]

[editor.indent-guides]
render = true
character = "▏" # other things "▏", "┆", "┊"
# skip-levels = 1

[keys.normal]
C-s = ":w"
esc = ":q"
A-up = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before", "collapse_selection"]
A-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before", "collapse_selection"]
A-down = ["extend_to_line_bounds", "delete_selection", "move_line_down", "goto_line_start", "paste_before", "collapse_selection"]
A-j = ["extend_to_line_bounds", "delete_selection", "move_line_down", "goto_line_start", "paste_before", "collapse_selection"]

[keys.normal.backspace]
r = ":rl"
c = ":config-open"
R = ":config-reload"
f = ":fmt"
t = ":o ~/.config/helix/themes/base16_terminal_edit.toml"
i = ":set lsp.display-inlay-hints false"
I = ":set lsp.display-inlay-hints true"

[keys.select]
C-s = ":w"

A-up = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before", "select_mode"]
A-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before", "select_mode"]
A-down = ["extend_to_line_bounds", "delete_selection", "move_line_down", "paste_before", "select_mode"]
A-j = ["extend_to_line_bounds", "delete_selection", "move_line_down", "paste_before", "select_mode"]

[keys.insert]
C-s = ":w"
C-v = ":clipboard-paste-before"
C-left = "move_prev_word_start"
C-right = "move_next_word_end"
A-p = "select_prev_sibling"
A-n = "select_next_sibling"
A-i = "shrink_selection"
A-o = "expand_selection"
