[[language]]
name = "cpp"
indent = { tab-width = 4, unit = " " }
auto-format = true
formatter = { command = "clang-format", args = ["-style={BasedOnStyle: llvm, IndentWidth: 4}"]}

[[language]]
name = "css"
auto-format = true
indent = { tab-width = 2, unit = "	" }
