[[language]]
name = "cpp"
indent = { tab-width = 4, unit = "    " }
auto-format = false

[language.formatter]
command = "clang-format"
args = ["""\
  -style={ \
  AllowShortIfStatementsOnASingleLine: WithoutElse, \
  AllowShortLoopsOnASingleLine: true, \
  BasedOnStyle: llvm, \
  IndentWidth: 4, \
  NamespaceIndentation: All, \
  IndentCaseLabels: true, \
  IndentPPDirectives: BeforeHash, \
  SpaceAfterTemplateKeyword: false, \
}"""]

[language-server.clangd]
args = ["--header-insertion=never"]
config = { fallbackFlags = [ "-std=c++17", "-Wall", "-Wconversion",
"-Wno-sign-conversion", "-Wno-shorten-64-to-32", "-Wno-unqualified-std-cast-call" ] }

[[language]]
name = "css"
auto-format = true
indent = { tab-width = 2, unit = "	" }
