complete -c taskbook -s a -l archive -d "Display archived items"
complete -c taskbook -s b -l begin -d "Start/pause task"
complete -c taskbook -s c -l check -d "Check/uncheck task"
complete -c taskbook -l clear -d "Delete all checked items"
complete -c taskbook -s y -l copy -d "Copy item description"
complete -c taskbook -s d -l delete -d "Delete item"
complete -c taskbook -s e -l edit -d "Edit item description"
complete -c taskbook -s f -l find -d "Search for items"
complete -c taskbook -s h -l help -d "Display help message"
complete -c taskbook -s l -l list -d "List item by attributes"
complete -c taskbook -s m -l move -d "Move item between boards"
complete -c taskbook -s n -l note -d "Create note"
complete -c taskbook -s p -l priority -d "Update priority of task"
complete -c taskbook -s r -l restore -d "Restore items from archive"
complete -c taskbook -s s -l star -d "Star/unstar item"
complete -c taskbook -s t -l task -d "Create task"
complete -c taskbook -s i -l timeline -d "Display timeline view"
complete -c taskbook -s v -l version -d "Display installed version"
