daemonize = true

max_history = 50

# Default: `$XDG_CACHE_HOME/clipcat/clipcatd-history`.
# history_file_path = "/home/<username>/.cache/clipcat/clipcatd-history"

# Default: `$XDG_RUNTIME_DIR/clipcatd.pid`.
# pid_file = "/run/user/<user-id>/clipcatd.pid"

primary_threshold_ms = 5000

[log]
# file_path = "/path/to/log/file"
emit_journald = true
emit_stdout = false
emit_stderr = false
level = "INFO"

[watcher]
enable_clipboard = true
enable_primary = false

sensitive_mime_types = ["x-kde-passwordManagerHint"]
denied_text_regex_patterns = []

filter_text_min_length = 1
filter_text_max_length = 20000000

capture_image = true
filter_image_max_size = 64000000 # 64MB

[grpc]
# Enable gRPC over HTTP.
enable_http = true
# Enable gRPC over Unix domain socket.
enable_local_socket = true
host = "127.0.0.1"
port = 45045
# Default: `$XDG_RUNTIME_DIR/clipcat/grpc.sock`.
# local_socket = "/run/user/1000/clipcat/grpc.sock"

[dbus]
enable = true
# identifier = "instance-0"

[desktop_notification]
enable = true
# Default value: `accessories-clipboard`.
# icon = "/path/to/the/icon"
timeout_ms = 2000
# If the length of plaintext is greater than or equal to `long_plaintext_length`,
# a desktop notification will be emitted.
# If this value is 0, no desktop notification.
long_plaintext_length = 2000


# [[snippets]]
