inherits = "base16_transparent"

"ui.menu" = { bg = "black" }
"ui.menu.selected" = { bg = "gray" }
"ui.help" = { bg = "black" }
"ui.menu.scroll" = { fg = "light-gray", bg = "black" }
"ui.popup" = { bg = "black" }
"ui.selection" = { bg = "background_highlight" }
"ui.statusline" = { fg = "white", bg = "black" }
"ui.statusline.inactive" = { fg = "gray", bg = "black" }
"ui.cursor" = { fg = "black", bg = "light-gray" }
"ui.cursor.primary" = { fg = "black", bg = "white" }
"ui.virtual.inlay-hint" = { fg = "gray" }
"ui.virtual.inlay-hint.parameter" = { fg = "gray" }
"ui.virtual.inlay-hint.type" = { fg = "gray" }
"ui.bufferline" = {  }
"ui.bufferline.active" = { bg = "gray" }

# zellij doesn't support undercurls yet :(
# "diagnostic.info" = { fg = "light-blue", modifiers = ["bold"], underline = { style = "line" } }
# "diagnostic.hint" = { fg = "light-gray", modifiers = ["bold"], underline = { style = "line" } }
# "diagnostic.debug" = { fg = "light-gray", modifiers = ["bold"], underline = { style = "line" } }
# "diagnostic.warning" = { fg = "light-yellow", modifiers = ["bold"], underline = { style = "line" } }
# "diagnostic.error" = { fg = "light-red", modifiers = ["bold"], underline = { style = "line" } }

"hint" = { }


"ui.statusline.normal" = { fg = "green", modifiers = ["bold", "reversed"] }
"ui.statusline.insert" = { fg = "blue", modifiers = ["bold", "reversed"] }
"ui.statusline.select" = { fg = "yellow", modifiers = ["bold", "reversed"] }

"ui.cursorline.primary" = { bg = "black" }

"ui.virtual.indent-guide" = "gray"
"ui.virtual.ruler" = { bg = "black" }

"comment" = { fg = "comment", modifiers = ["italic"] }
"punctuation" = { fg = "comment" }

[palette]
comment = "#565f89"
background_highlight = "#373d5a"
