add_newline = false

command_timeout = 2_000

format = """$time $all"""

# right_format = """$time"""

[character]
success_symbol = ""
error_symbol = ""
disabled = true

[cmd_duration]
min_time = 500
disabled = true

[directory]
# truncation_symbol = "…/"
format = "[ ](bg:blue)[ $path ](bg:black) "
use_os_path_sep = false

[git_branch]
symbol = ""
format = '[ ](bg:purple)[ $symbol$branch ](bg:black)'

[git_status]
format = '([$all_status$ahead_behind ]($style)) '
style = "fg:cyan bold bg:black"
deleted = "-"

[rust]
symbol = "rs"
version_format = ""
format = '[ ](bg:red)[ $symbol$version ](bg:black) '

[nodejs]
symbol = "node"
version_format = ""
format = '[ ](bg:green)[ $symbol$version ](bg:black) '

[c]
symbol = "C"
version_format = ""
format = '[ ](bg:green)[ $symbol$version ](bg:black) '

[status]
format = '[\[$status\]](bold red) '
disabled = false

[time]
format = "[ ](bg:yellow)[ $time ](bg:black)"
time_format = '%R'
style = 'yellow bold'
disabled = false

[line_break]
disabled = true

[package]
disabled = true
