add_newline = false

command_timeout = 2_000

format = """$all"""

right_format = """$cmd_duration$time"""

[character]
format = "λ "

[cmd_duration]
disabled = false
style = "yellow"
format = "[$duration]($style) "
min_time = 100
show_milliseconds = true

[directory]
# truncation_symbol = "…/"
truncation_length = 1
fish_style_pwd_dir_length = 1
use_os_path_sep = false
style = 'blue'

[git_branch]
symbol = ""
style = "purple"
format = '[$symbol$branch]($style)'

[git_status]
style = "bold cyan"
format = '([$all_status$ahead_behind]($style)) '
deleted = "-"

[status]
disabled = false
format = '[\[$status\]](bold red) '

[time]
disabled = false
style = 'yellow'
time_format = '%R'
format = '''[\[$time\]]($style)'''

[line_break]
disabled = true

[package]
disabled = true

[rust]
symbol = "rs"
format = '[$symbol]($style) '

[nodejs]
symbol = "node"
format = '[$symbol]($style) '

[c]
symbol = "C"
format = '[$symbol]($style) '

[cpp]
symbol = "C++"
format = '[$symbol]($style) '

[cmake]
symbol = 'cmake'
format = '[$symbol]($style) '

[golang]
symbol = 'go'
format = '[$symbol]($style) '

[java]
symbol = 'java'
format = '[$symbol]($style) '

[julia]
symbol = 'jl'
format = '[$symbol]($style) '

[kotlin]
symbol = 'kt'
format = '[$symbol]($style) '

[lua]
symbol = 'lua'
format = '[$symbol]($style) '

[nim]
symbol = 'nim'
format = '[$symbol]($style) '

[nix_shell]
format = '[$symbol$state( \($name\))]($style) '

[python]
format = '[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style) '

[sudo]
format = '[as $symbol]($style) '

[typst]
symbol = 'typ'
format = '[$symbol]($style) '

[zig]
format = '[$symbol]($style) '
