add_newline = false

command_timeout = 2_000

format = """$all"""

right_format = """$cmd_duration$time"""

[character]
format = "λ "

[cmd_duration]
disabled = false
style = "yellow"
format = "[$duration]($style) "
min_time = 100
show_milliseconds = true

[directory]
# truncation_symbol = "…/"
truncation_length = 1
fish_style_pwd_dir_length = 1
use_os_path_sep = false
style = 'blue'

[git_branch]
symbol = ""
style = "purple"
format = '[$symbol$branch]($style)'

[git_status]
style = "bold cyan"
format = '([$all_status$ahead_behind]($style)) '
deleted = "-"

[rust]
symbol = "rs"
version_format = ""
format = '[$symbol$version]($style) '

[nodejs]
symbol = "node"
format = '[$symbol]($style) '

[status]
disabled = false
format = '[\[$status\]](bold red) '

[time]
disabled = false
style = 'yellow'
time_format = '%R'
format = '''[\[$time\]]($style)'''

[line_break]
disabled = true

[package]
disabled = true
